### ISSUE TITLE
Ripley issues! Maybe?

### ISSUE THREAD

**Issue by benj8560** [sojourn-13/sojourn-station#4710] opened 2023-07-15 02:08 UTC
Not fully sure if this is a bug. But it's sure as hell a issue regardless. It's a well known SS13 staple that the best way to transport a SM is via a ripley with a clamp. 

Today I tried to do this and apon trying to do this got ashed INSIDE of the mech. The mech remaining totally fine. It was done on a SM shard if that's at all relevant but pretty sure SMs and SM shards are virtually identical with just tweaked stats so doubt it. My first guess might be it's something to do with that highly cursed interact with computers/machines mechanic we have while inside of mechs given how the other issues I've seen stem from that.

at a minimum this should at least be better publicized to never clamp them since I've heard it more then once on this sever.

**Comment by cdb-is-not-good** [comment] 2023-07-15 05:33
To clarify, you got ashed by trying to load the supermatter into the ripley? or by stepping into it?

**Comment by benj8560** [comment] 2023-07-15 14:10
I came to a full stop next to it and clicked with the clamp

**Comment by benj8560** [comment] 2023-07-15 14:11
walking into it should proly ash the mech I always assumed the clamping to be some delicate thing like dragging it. Stumbling into it well that's on the player

**Comment by benj8560** [comment] 2023-07-15 14:18
also suppose i should point out the mech did not eject apon me being ashed (makes no sense) . And the mech was left unscathed so clearly the code does not account for this at all or is broken if it does.

**Comment by cdb-is-not-good** [comment] 2023-07-16 04:31
Doing some research, this is apparently an intended behavior. Janky as fuck, but intended. Apparently loading a supermatter would reverse delam and cause some weird behavior- though I do think the Ripley should likely /also/ poof.

**Comment by cdb-is-not-good** [comment] 2023-07-24 05:53
Closing for now, not technically an unintended behavior. Discussion about changing this can just take place in the discord.

**Closed by cdb-is-not-good** 2023-07-24 05:53 UTC
