### ISSUE TITLE
Ultra does not let you use body scanners

### ISSUE THREAD

**Issue by benj8560** [sojourn-13/sojourn-station#4706] opened 2023-07-13 14:07 UTC
in the name. Ultra surgeon alone does not bypass the skill check for body scanners alone.

**Comment by cdb-is-not-good** [comment] 2023-07-15 05:39
Technically not a bug, but I'm open to changing this.

**Comment by cdb-is-not-good** [comment] 2023-07-24 05:54
Closing for now. Not technically a bug, and discussion about if it should be changed can just go on the discord.

**Closed by cdb-is-not-good** 2023-07-24 05:54 UTC
